version: '3.8'

services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    volumes:
      - memgraph-data:/var/lib/memgraph

  bitcoin-funds-flow-indexer:
    build:
        context: ../../..
        dockerfile: Dockerfile
    command: ["python", "neurons/miners/bitcoin/funds_flow/indexer.py"]

volumes:
  memgraph-data:
