version: '3.8'

services:
  memgraph-funds-flow:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph

  bitcoin-funds-flow-indexer:
    image: blockchain_insights_base
    command: ["./scripts/run_indexer_bitcoin_funds_flow.sh"]
    environment:
      - NODE_RPC_URL=${NODE_RPC_URL}

volumes:
   memgraph-funds-flow-data:
