version: '3.8'

services:
  memgraph-funds-flow:
    image: memgraph/memgraph-mage:latest
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph

  bitcoin-funds-flow-indexer:
    image: blockchain_insights_base
    command: ["python", "neurons/miners/bitcoin/funds_flow/indexer.py"]
    environment:
      - NODE_RPC_URL=${NODE_RPC_URL}
      - GRAPH_DB_URL=${GRAPH_DB_URL}
      - PYTHONPATH=.

volumes:
   memgraph-funds-flow-data:
