name: build docker image

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name to build from'
        required: true
        default: 'dev'
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/blockchain-data-subnet
          VERSION=${{ github.event.inputs.version }}
          FULL_TAG="$IMAGE_NAME:${VERSION}"
          docker build --tag $FULL_TAG .
          docker push $FULL_TAG
