name: build docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@funds_flow
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/} # Extract branch name from GITHUB_REF
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/blockchain-data-subnet
          VERSION=${{ github.event.inputs.version }}
          # Combine branch name and version into the tag
          FULL_TAG="$IMAGE_NAME:$BRANCH_NAME-${VERSION}"
          docker build --tag $FULL_TAG .
          docker push $FULL_TAG

